#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use hiqdev\composer\config\Builder;

require __DIR__ . '/vendor/autoload.php';

$config = require Builder::path('console');

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
